"""
Offline LLM provider for running and testing the agent harness without API
keys or a local model server.

    from app.core.harness.mock_llm import install_mock_provider
    mock = install_mock_provider()          # registers provider "mock"
    mock.queue({"content": '{"summary": "..."}'})

With nothing queued, the mock answers with a small generic JSON payload so
agents can run end-to-end and their parsing / flow logic can be exercised.
"""

import json
from collections import deque
from typing import Any, Callable, Deque, Dict, List, Optional, Union

MOCK_PROVIDER = "mock"

ScriptItem = Union[Dict[str, Any], Callable[[Dict[str, Any]], Dict[str, Any]], Exception]

DEFAULT_RESPONSE = {
    "summary": "Mock analysis generated by the offline harness provider.",
    "reasoning": "This response was produced by MockLLMClient; no model was called.",
    "recommendation": "HOLD",
    "confidence": 0.5,
    "key_findings": [],
    "risks": [],
}


class MockLLMClient:
    """Scripted stand-in with the same generate() contract as the real clients."""

    provider = MOCK_PROVIDER
    max_context = 128_000

    def __init__(self, default: Optional[Dict[str, Any]] = None):
        self.default = default or {"content": json.dumps(DEFAULT_RESPONSE)}
        self._script: Deque[ScriptItem] = deque()
        self.calls: List[Dict[str, Any]] = []

    def queue(self, *items: ScriptItem) -> "MockLLMClient":
        """Queue responses: a result dict, a callable(request) → dict, or an
        exception instance to raise."""
        self._script.extend(items)
        return self

    def tool_call(self, name: str, **args) -> "MockLLMClient":
        """Queue a native tool-call turn."""
        return self.queue({"content": "", "function_calls": [{"name": name, "args": args}]})

    def reset(self) -> None:
        self._script.clear()
        self.calls.clear()

    async def generate(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        tools: Optional[List[Dict]] = None,
        **kwargs,
    ) -> Dict[str, Any]:
        request = {
            "prompt": prompt,
            "system_prompt": system_prompt,
            "tools": tools,
            **kwargs,
        }
        self.calls.append(request)

        item = self._script.popleft() if self._script else self.default
        if isinstance(item, Exception):
            raise item
        if callable(item):
            item = item(request)
        return {"content": "", "function_calls": [], **item}


def install_mock_provider(client: Optional[MockLLMClient] = None) -> MockLLMClient:
    """Register `client` (or a fresh MockLLMClient) as LLM provider "mock"."""
    from app.core.llm import register_llm_client

    client = client or MockLLMClient()
    register_llm_client(MOCK_PROVIDER, lambda: client)
    return client


def route_all_agents_to(provider: str) -> None:
    """Point every agent (and the default fallback) at one provider."""
    from app.core.llm.model_router import get_model_router

    router = get_model_router()
    for agent in list(router.agent_routing):
        router.agent_routing[agent] = provider
    router.fallback_provider = provider
    router.cloud_fallback = provider
